---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-components-flux-helm
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
    # tag: v0.1.0
  url: https://github.com/tanviranadive/cluster-components-flux-helm.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: components
  namespace: flux-system
spec:
  chart:
    spec:
      chart: .
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: cluster-components-flux-helm
  interval: 10m0s
  values:
    departmentCode: 275
    alpha:
      values:
        replicaCount: 1
    bravo:
      values:
        replicaCount: 1
    charlie:
      enabled: false
    keda:
      values:
        resources:
          operator:
            limits:
              cpu: 75m
        operator:
          replicaCount: 3
